"""add risk metrics table

Revision ID: 106809263507
Revises: d4d2956d47d6
Create Date: 2026-06-15 23:24:38.445633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '106809263507'
down_revision: Union[str, Sequence[str], None] = 'd4d2956d47d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_metrics',
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('volatility', sa.Float(), nullable=False),
    sa.Column('drawdown', sa.Float(), nullable=False),
    sa.Column('var_95', sa.Float(), nullable=False),
    sa.Column('expected_shortfall', sa.Float(), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column(
        'risk_category',
        sa.String(length=30),
        nullable=False
    ),
    sa.PrimaryKeyConstraint('symbol', 'timeframe', 'timestamp')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('risk_metrics')
    # ### end Alembic commands ###
