"""create research_reports table

Revision ID: 565a93d9022c
Revises: b7ddcb9cd2c1
Create Date: 2026-06-07 02:38:38.023514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '565a93d9022c'
down_revision: Union[str, Sequence[str], None] = 'b7ddcb9cd2c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('research_reports',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('company', sa.String(length=100), nullable=False),
    sa.Column('report_type', sa.String(length=50), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('report_data', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_reports_company'), 'research_reports', ['company'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_research_reports_company'), table_name='research_reports')
    op.drop_table('research_reports')
    # ### end Alembic commands ###
