"""create recommendations table

Revision ID: 6a2623dedd88
Revises: c9876a70a8eb
Create Date: 2026-06-07 02:34:27.544907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a2623dedd88'
down_revision: Union[str, Sequence[str], None] = 'c9876a70a8eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recommendations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('recommendation', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('explanation', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_symbol'), 'recommendations', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recommendations_symbol'), table_name='recommendations')
    op.drop_table('recommendations')
    # ### end Alembic commands ###
