"""create agent_outputs table

Revision ID: b7ddcb9cd2c1
Revises: 6a2623dedd88
Create Date: 2026-06-07 02:36:56.418408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7ddcb9cd2c1'
down_revision: Union[str, Sequence[str], None] = '6a2623dedd88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_outputs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('agent_name', sa.String(length=100), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('output', sa.JSON(), nullable=False),
    sa.Column('execution_time', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_outputs_symbol'), 'agent_outputs', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_outputs_symbol'), table_name='agent_outputs')
    op.drop_table('agent_outputs')
    # ### end Alembic commands ###
