"""add news feature daily table

Revision ID: c422ca671609
Revises: 972041b4bdc8
Create Date: 2026-07-07 11:57:44.405787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c422ca671609'
down_revision: Union[str, Sequence[str], None] = '972041b4bdc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_features_daily',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('news_count', sa.Integer(), nullable=False),
    sa.Column('positive_count', sa.Integer(), nullable=False),
    sa.Column('negative_count', sa.Integer(), nullable=False),
    sa.Column('neutral_count', sa.Integer(), nullable=False),
    sa.Column('positive_ratio', sa.Float(), nullable=False),
    sa.Column('negative_ratio', sa.Float(), nullable=False),
    sa.Column('avg_confidence', sa.Float(), nullable=False),
    sa.Column('positive_confidence_mean', sa.Float(), nullable=False),
    sa.Column('negative_confidence_mean', sa.Float(), nullable=False),
    sa.Column('neutral_confidence_mean', sa.Float(), nullable=False),
    sa.Column('sentiment_score', sa.Float(), nullable=False),
    sa.Column('earnings_count', sa.Integer(), nullable=False),
    sa.Column('funding_count', sa.Integer(), nullable=False),
    sa.Column('regulatory_count', sa.Integer(), nullable=False),
    sa.Column('macro_count', sa.Integer(), nullable=False),
    sa.Column('mergers_acquisitions_count', sa.Integer(), nullable=False),
    sa.Column('event_score', sa.Float(), nullable=False),
    sa.Column('sentiment_momentum', sa.Float(), nullable=False),
    sa.Column('event_intensity', sa.Float(), nullable=False),
    sa.Column('positive_confidence', sa.Float(), nullable=False),
    sa.Column('negative_confidence', sa.Float(), nullable=False),
    sa.Column('neutral_confidence', sa.Float(), nullable=False),
    sa.Column('event_article_ratio', sa.Float(), nullable=False),
    sa.Column('dominant_sentiment', sa.String(length=20), nullable=False),
    sa.Column('has_earnings_event', sa.Integer(), nullable=False),
    sa.Column('has_regulatory_event', sa.Integer(), nullable=False),
    sa.Column('has_funding_event', sa.Integer(), nullable=False),
    sa.Column('has_ma_event', sa.Integer(), nullable=False),
    sa.Column('news_count_3d', sa.Float(), nullable=False),
    sa.Column('sentiment_score_3d', sa.Float(), nullable=False),
    sa.Column('event_score_3d', sa.Float(), nullable=False),
    sa.Column('news_count_7d', sa.Float(), nullable=False),
    sa.Column('sentiment_score_7d', sa.Float(), nullable=False),
    sa.Column('event_score_7d', sa.Float(), nullable=False),
    sa.Column('rolling_news_momentum', sa.Float(), nullable=False),
    sa.Column('news_attention_score', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('news_features_daily')
    # ### end Alembic commands ###
