"""upgrade news article schema

Revision ID: d4d2956d47d6
Revises: 60940bb75a69
Create Date: 2026-06-13 20:46:40.874779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4d2956d47d6'
down_revision: Union[str, Sequence[str], None] = '60940bb75a69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'news_articles',
        sa.Column(
            'provider',
            sa.String(length=50),
            nullable=True
        )
    )

    op.add_column(
        'news_articles',
        sa.Column(
            'provider_article_id',
            sa.String(length=200),
            nullable=True
        )
    )

    op.add_column(
        'news_articles',
        sa.Column(
            'events',
            sa.Text(),
            nullable=True
        )
    )
    op.drop_column('news_articles', 'event_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news_articles', sa.Column('event_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('news_articles', 'events')
    op.drop_column('news_articles', 'provider_article_id')
    op.drop_column('news_articles', 'provider')
    # ### end Alembic commands ###
