"""add technical indicators table

Revision ID: e6ffbcdc835b
Revises: 0c025846fce6
Create Date: 2026-06-07 22:41:07.900666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6ffbcdc835b'
down_revision: Union[str, Sequence[str], None] = '0c025846fce6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('technical_indicators',
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rsi', sa.Float(), nullable=False),
    sa.Column('mfi', sa.Float(), nullable=False),
    sa.Column('sma_20', sa.Float(), nullable=False),
    sa.Column('ema_20', sa.Float(), nullable=False),
    sa.Column('macd', sa.Float(), nullable=False),
    sa.Column('macd_signal', sa.Float(), nullable=False),
    sa.Column('adx', sa.Float(), nullable=False),
    sa.Column('atr', sa.Float(), nullable=False),
    sa.Column('obv', sa.Float(), nullable=False),
    sa.Column('vwap', sa.Float(), nullable=False),
    sa.Column('bb_upper', sa.Float(), nullable=False),
    sa.Column('bb_middle', sa.Float(), nullable=False),
    sa.Column('bb_lower', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('symbol', 'timestamp')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('technical_indicators')
    # ### end Alembic commands ###
